export const CHANGE_ADDRESS = 'CHANGE_ADDRESS';
export const FETCH_AIR_QUALITY_SUCCESS = 'FETCH_AIR_QUALITY_SUCCESS';
export const CHANGE_ERROR_MESSAGE = 'CHANGE_ERROR_MESSAGE';
export const ADD_TO_HISTORY = 'ADD_TO_HISTORY';
